/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Enterprise.HospitalEnterprise;
import Business.MainUserAccount.MainUserAccount;
import Business.Network.Network;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.WorkQueue.AppointmentWorkRequest;
import Business.WorkQueue.WorkRequest;
import com.sun.glass.events.KeyEvent;
import java.awt.CardLayout;
import java.text.DateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Achal Sancheti
 */
public class BookAppointmentJPanel extends javax.swing.JPanel {

    JPanel userProcessContainer;
    MainUserAccount account;
    Enterprise enterprise;
    EcoSystem business;
    
    DateFormat df = DateFormat.getDateInstance();
    
    /**
     * Creates new form BookAppointmentJPanel
     */
    public BookAppointmentJPanel(JPanel userProcessContainer,MainUserAccount account,Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.enterprise=enterprise;
        this.business=business;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) dateTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request: account.getWorkQueue().getWorkRequestList()){
            if(request instanceof AppointmentWorkRequest){
            
            Object[] row = new Object[3];

            String date = ((AppointmentWorkRequest)request).getDate1();
            row[0] = request;
            String time = ((AppointmentWorkRequest)request).getTime1();
            row[1] = time;
            row[2] = request.getStatus();
            
            model.addRow(row);
        }}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dateTable = new javax.swing.JTable();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        submitButton = new javax.swing.JButton();
        timeTextField = new javax.swing.JFormattedTextField();
        date = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dateTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Time", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(dateTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 710, 140));

        backButton.setBackground(new java.awt.Color(0, 0, 0));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("<<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 520, -1, 33));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Date:");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Time:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 330, -1, -1));

        submitButton.setBackground(new java.awt.Color(0, 0, 0));
        submitButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        submitButton.setForeground(new java.awt.Color(255, 255, 255));
        submitButton.setText("Submit");
        submitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitButtonActionPerformed(evt);
            }
        });
        add(submitButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 400, 90, 33));

        timeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                timeTextFieldKeyTyped(evt);
            }
        });
        add(timeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 320, 200, 30));
        add(date, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, 200, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void submitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitButtonActionPerformed
            
        if(!date.getDate().equals("")&&!timeTextField.getText().isEmpty()){
            String da = df.format(date.getDate());          
            String ti = timeTextField.getText();

            
        AppointmentWorkRequest app = new AppointmentWorkRequest();

        app.setStatus("Request Sent");
        app.setDate1(da);
        app.setTime1(ti);
        
        Enterprise ent = null;
        Organization org = null;
        for(Network network : business.getNetworkList()){
            for(Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()){
                if(enterprise instanceof HospitalEnterprise)
                        ent=enterprise;
                
                
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof DoctorOrganization){
                org = organization;
                break;
            }
        }
            }
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(app);
            account.getWorkQueue().getWorkRequestList().add(app);
        }
        
        JOptionPane.showMessageDialog(null, "Request Has Been Sent To Doctor","Success",JOptionPane.INFORMATION_MESSAGE);
        populateTable();
        timeTextField.setText("");
        }else{
        JOptionPane.showMessageDialog(null, "Please Provide Both Date and Time","Error",JOptionPane.ERROR_MESSAGE);
        
        }
            
    }//GEN-LAST:event_submitButtonActionPerformed

    private void timeTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_timeTextFieldKeyTyped
        char c = evt.getKeyChar();
        if(!(c=='0'||c=='1'||c=='2'||c=='3'||c=='4'||c=='5'||c=='6'||c=='7'||c=='8'||c=='9'||c==KeyEvent.VK_BACKSPACE||c==KeyEvent.VK_DELETE||c==KeyEvent.VK_SPACE||c==':'||c=='a'||c=='m'||c=='p'))
        {
        evt.consume();
        JOptionPane.showMessageDialog(null, "Please Enter Correct Value for date","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_timeTextFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private com.toedter.calendar.JDateChooser date;
    private javax.swing.JTable dateTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton submitButton;
    private javax.swing.JFormattedTextField timeTextField;
    // End of variables declaration//GEN-END:variables
}
