/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRelativeRole;

import Business.Enterprise.Enterprise;
import Business.MainUserAccount.MainUserAccount;
import Business.Organization.Organization;
import Business.Organization.PatientRelativeOrganization;
import UserInterface.DoctorRole.CalculateVitalSignJPanel;
import java.awt.CardLayout;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Achal Sancheti
 */
public class PatientRelativeJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    MainUserAccount userAccount;
    PatientRelativeOrganization patientRelativeOrganization;
    Organization organization;

    /**
     * Creates new form PatientRelativeJPanel
     */
    public PatientRelativeJPanel(JPanel userProcessContainer,Enterprise enterprise,MainUserAccount userAccount,PatientRelativeOrganization organization) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.userAccount=userAccount;
        this.organization=organization;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seelocationButton = new javax.swing.JButton();
        unlockdoorButton = new javax.swing.JButton();
        seedoctormessageButton = new javax.swing.JButton();
        seepatientmessageButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        seelocationButton.setBackground(new java.awt.Color(0, 0, 0));
        seelocationButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        seelocationButton.setForeground(new java.awt.Color(255, 255, 255));
        seelocationButton.setText("See Patient Location");
        seelocationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seelocationButtonActionPerformed(evt);
            }
        });
        add(seelocationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 330, 260, 40));

        unlockdoorButton.setBackground(new java.awt.Color(0, 0, 0));
        unlockdoorButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        unlockdoorButton.setForeground(new java.awt.Color(255, 255, 255));
        unlockdoorButton.setText("Unlock Doors");
        unlockdoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unlockdoorButtonActionPerformed(evt);
            }
        });
        add(unlockdoorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 400, 260, 40));

        seedoctormessageButton.setBackground(new java.awt.Color(0, 0, 0));
        seedoctormessageButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        seedoctormessageButton.setForeground(new java.awt.Color(255, 255, 255));
        seedoctormessageButton.setText("See Doctor's Emergency Message");
        seedoctormessageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seedoctormessageButtonActionPerformed(evt);
            }
        });
        add(seedoctormessageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 260, 40));

        seepatientmessageButton.setBackground(new java.awt.Color(0, 0, 0));
        seepatientmessageButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        seepatientmessageButton.setForeground(new java.awt.Color(255, 255, 255));
        seepatientmessageButton.setText("See Patient's Emergency Message");
        seepatientmessageButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seepatientmessageButtonActionPerformed(evt);
            }
        });
        add(seepatientmessageButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 260, 40));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 48)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 153));
        jLabel2.setText("Relative Work Area");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 440, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/relative.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void seelocationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seelocationButtonActionPerformed

        int dialogButton = JOptionPane.YES_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Would You Like To See The Location Of Patient?");
        if(dialogResult==JOptionPane.YES_OPTION){
        if(Desktop.isDesktopSupported())
        {
            try {
                Desktop.getDesktop().browse(new URI("https://www.google.com/maps/place/Northeastern+University/@42.3398106,-71.0913604,17z/data=!3m1!4b1!4m2!3m1!1s0x89e37a1999cf5ce1:0xc97b00e66522b98c"));
            } catch (URISyntaxException ex) {
                Logger.getLogger(CalculateVitalSignJPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(CalculateVitalSignJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        }
    }//GEN-LAST:event_seelocationButtonActionPerformed

    private void unlockdoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unlockdoorButtonActionPerformed
        
            UnlockDoorJPanel unlockDoorJPanel = new UnlockDoorJPanel(userProcessContainer, enterprise, userAccount,(PatientRelativeOrganization)organization);
            userProcessContainer.add("UnlockDoorJPanel", unlockDoorJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_unlockdoorButtonActionPerformed

    private void seepatientmessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seepatientmessageButtonActionPerformed
        
            EmergencyMessageJPanel emergencyMessageJPanel = new EmergencyMessageJPanel(userProcessContainer, enterprise, userAccount,(PatientRelativeOrganization)organization);
            userProcessContainer.add("EmergencyMessageJPanel", emergencyMessageJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_seepatientmessageButtonActionPerformed

    private void seedoctormessageButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seedoctormessageButtonActionPerformed
        
            DoctorEmMessageJPanel doctorEmMessageJPanel = new DoctorEmMessageJPanel(userProcessContainer, enterprise, userAccount,(PatientRelativeOrganization)organization);
            userProcessContainer.add("DoctorEmMessageJPanel", doctorEmMessageJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_seedoctormessageButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton seedoctormessageButton;
    private javax.swing.JButton seelocationButton;
    private javax.swing.JButton seepatientmessageButton;
    private javax.swing.JButton unlockdoorButton;
    // End of variables declaration//GEN-END:variables
}
