/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRelativeRole;

import Business.Enterprise.Enterprise;
import Business.MainUserAccount.MainUserAccount;
import Business.Organization.PatientRelativeOrganization;
import Business.WorkQueue.DoctorMessageWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Achal Sancheti
 */
public class DoctorEmMessageJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    MainUserAccount userAccount;
    PatientRelativeOrganization patientRelativeOrganization;

    /**
     * Creates new form DoctorMessageJPanel
     */
    public DoctorEmMessageJPanel(JPanel userProcessContainer,Enterprise enterprise,MainUserAccount userAccount,PatientRelativeOrganization patientRelativeOrganization) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.userAccount=userAccount;
        this.patientRelativeOrganization=patientRelativeOrganization;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) messageTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request: patientRelativeOrganization.getWorkQueue().getWorkRequestList()){
            if(request instanceof DoctorMessageWorkRequest){
            
            Object[] row = new Object[4];

            row[0] = request.getDate();
            row[1] = request.getTime();
            String door = ((DoctorMessageWorkRequest)request).getMessage();
            row[2] = door;
            row[3] = request.getStatus();
            
            model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        messageTable = new javax.swing.JTable();
        changestatusButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        messageTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Date", "Time", "Message", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(messageTable);
        if (messageTable.getColumnModel().getColumnCount() > 0) {
            messageTable.getColumnModel().getColumn(2).setPreferredWidth(200);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 730, 120));

        changestatusButton.setBackground(new java.awt.Color(0, 0, 0));
        changestatusButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        changestatusButton.setForeground(new java.awt.Color(255, 255, 255));
        changestatusButton.setText("Change Status");
        changestatusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changestatusButtonActionPerformed(evt);
            }
        });
        add(changestatusButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, 140, 40));

        backButton.setBackground(new java.awt.Color(0, 0, 0));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("<<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, -1, 33));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 80, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/message.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 60, 530, 420));
    }// </editor-fold>//GEN-END:initComponents

    private void changestatusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changestatusButtonActionPerformed
        
        int selectedRow = messageTable.getSelectedRow();

        if (selectedRow >= 0) {
            for (WorkRequest request: patientRelativeOrganization.getWorkQueue().getWorkRequestList()){
                if(request instanceof DoctorMessageWorkRequest){
                    request.setStatus("Seen");
                    populateTable();
                }}} else {
                    JOptionPane.showMessageDialog(null, "Choose a request to process.","Error",JOptionPane.ERROR_MESSAGE);
                    return;
                }
    }//GEN-LAST:event_changestatusButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JButton changestatusButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable messageTable;
    // End of variables declaration//GEN-END:variables
}
