/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRelativeRole;

import Business.Enterprise.Enterprise;
import Business.MainUserAccount.MainUserAccount;
import Business.Organization.PatientRelativeOrganization;
import Business.WorkQueue.DoorWorkRequest;
import Business.WorkQueue.WorkRequest;
import UserInterface.DoctorRole.CalculateVitalSignJPanel;
import java.awt.CardLayout;
import java.awt.Desktop;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Achal Sancheti
 */
public class UnlockDoorJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    MainUserAccount userAccount;
    PatientRelativeOrganization patientRelativeOrganization;

    /**
     * Creates new form UnlockDoorJPanel
     */
    public UnlockDoorJPanel(JPanel userProcessContainer,Enterprise enterprise,MainUserAccount userAccount,PatientRelativeOrganization patientRelativeOrganization) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.userAccount=userAccount;
        this.patientRelativeOrganization=patientRelativeOrganization;
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) doorTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request: patientRelativeOrganization.getWorkQueue().getWorkRequestList()){
            if(request instanceof DoorWorkRequest){
            
            Object[] row = new Object[4];

            String door = ((DoorWorkRequest)request).getDoor();
            row[0] = request;
            row[1] = request.getStatus();
            row[2] = request.getDate();
            row[3] = request.getTime();
            
            model.addRow(row);
        }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        doorTable = new javax.swing.JTable();
        unlockdoorButton = new javax.swing.JButton();
        nearbyhospitalButton = new javax.swing.JButton();
        nearbystoreButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        doorTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Door", "Status", "Date", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(doorTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 91, 712, 136));

        unlockdoorButton.setBackground(new java.awt.Color(0, 0, 0));
        unlockdoorButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        unlockdoorButton.setForeground(new java.awt.Color(255, 255, 255));
        unlockdoorButton.setText("Unlock Door");
        unlockdoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unlockdoorButtonActionPerformed(evt);
            }
        });
        add(unlockdoorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 140, 40));

        nearbyhospitalButton.setBackground(new java.awt.Color(0, 0, 0));
        nearbyhospitalButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nearbyhospitalButton.setForeground(new java.awt.Color(255, 255, 255));
        nearbyhospitalButton.setText("See Nearby Hospitals");
        nearbyhospitalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nearbyhospitalButtonActionPerformed(evt);
            }
        });
        add(nearbyhospitalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 180, 40));

        nearbystoreButton.setBackground(new java.awt.Color(0, 0, 0));
        nearbystoreButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        nearbystoreButton.setForeground(new java.awt.Color(255, 255, 255));
        nearbystoreButton.setText("See Nearby Drug Stores");
        nearbystoreButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nearbystoreButtonActionPerformed(evt);
            }
        });
        add(nearbystoreButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, -1, 40));

        backButton.setBackground(new java.awt.Color(0, 0, 0));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("<<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 540, -1, 33));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 90, -1, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/door.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 40, 530, 510));
    }// </editor-fold>//GEN-END:initComponents

    private void unlockdoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unlockdoorButtonActionPerformed
        
        int selectedRow = doorTable.getSelectedRow();

        if (selectedRow >= 0) {
        int dialogButton = JOptionPane.YES_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Would You Like To Unlock Door?");
        if(dialogResult==JOptionPane.YES_OPTION){
            WorkRequest request = (WorkRequest) doorTable.getValueAt(selectedRow, 0);
            if (request.getStatus().equalsIgnoreCase("Unlocked")) {
                JOptionPane.showMessageDialog(null, "Already Unlocked.","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }else{
                String date = new java.text.SimpleDateFormat("MM/dd/yyyy").format(new Date());
                String time = new java.text.SimpleDateFormat("h:mm:ss a").format(new Date());
                request.setStatus("Unlocked");
                request.setDate(date);
                request.setTime(time);
                populateTable();
                JOptionPane.showMessageDialog(null, "Door Has Been Unlocked Successfully","Success",JOptionPane.INFORMATION_MESSAGE);
            } 
        }
        }else {
                JOptionPane.showMessageDialog(null, "Choose A Door To Process.","Error",JOptionPane.ERROR_MESSAGE);
                return;
            }
    }//GEN-LAST:event_unlockdoorButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void nearbyhospitalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nearbyhospitalButtonActionPerformed
        
        int dialogButton = JOptionPane.YES_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Would You Like To See Nearby Hospitals?");
        if(dialogResult==JOptionPane.YES_OPTION){
        if(Desktop.isDesktopSupported())
        {
            try {
                Desktop.getDesktop().browse(new URI("https://www.google.com/maps/search/medical+hospital/@42.337781,-71.1074531,16z"));
            } catch (URISyntaxException ex) {
                Logger.getLogger(CalculateVitalSignJPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(CalculateVitalSignJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        }
    }//GEN-LAST:event_nearbyhospitalButtonActionPerformed

    private void nearbystoreButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nearbystoreButtonActionPerformed
        
        int dialogButton = JOptionPane.YES_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Would You Like To See Nearby Drug Stores?");
        if(dialogResult==JOptionPane.YES_OPTION){
        if(Desktop.isDesktopSupported())
        {
            try {
                Desktop.getDesktop().browse(new URI("https://www.google.com/maps/search/nearby+drug+stores/@42.3357713,-71.1241299,14z/data=!3m1!4b1"));
            } catch (URISyntaxException ex) {
                Logger.getLogger(CalculateVitalSignJPanel.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(CalculateVitalSignJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        }
    }//GEN-LAST:event_nearbystoreButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTable doorTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nearbyhospitalButton;
    private javax.swing.JButton nearbystoreButton;
    private javax.swing.JButton unlockdoorButton;
    // End of variables declaration//GEN-END:variables
}
