/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ReceptionistRole;


import Business.Enterprise.Enterprise;
import Business.Organization.DoctorOrganization;
import Business.Organization.Organization;
import Business.MainUserAccount.MainUserAccount;
import Business.WorkQueue.DoctorTestWorkRequest;
import com.sun.glass.events.KeyEvent;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Achal Sancheti
 */
public class DoctorTestWorkRequestJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private MainUserAccount userAccount;

    /**
     * Creates new form NurseTestWorkRequestJPanel
     */
    public DoctorTestWorkRequestJPanel(JPanel userProcessContainer, MainUserAccount account, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        patientnameTextField = new javax.swing.JTextField();
        dateTextField = new javax.swing.JTextField();
        requestTestButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        timeTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        messageTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ageTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Patient Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Date");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 260, -1, -1));

        patientnameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                patientnameTextFieldKeyTyped(evt);
            }
        });
        add(patientnameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 100, -1));

        dateTextField.setEnabled(false);
        add(dateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 260, 100, -1));

        requestTestButton.setBackground(new java.awt.Color(0, 0, 0));
        requestTestButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        requestTestButton.setForeground(new java.awt.Color(255, 255, 255));
        requestTestButton.setText("Request Test");
        requestTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestButtonActionPerformed(evt);
            }
        });
        add(requestTestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 370, -1, 40));

        backButton.setBackground(new java.awt.Color(0, 0, 0));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("<<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("ID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 220, -1, -1));

        idTextField.setEnabled(false);
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });
        add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 220, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Time");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, -1, -1));

        timeTextField.setEnabled(false);
        add(timeTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 100, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Age");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 140, -1, -1));
        add(messageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, 100, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/patient info.jpg"))); // NOI18N
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 100, 460, 260));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Message");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 180, -1, -1));

        ageTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                ageTextFieldKeyTyped(evt);
            }
        });
        add(ageTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 100, -1));

        jLabel8.setText("jLabel8");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 180, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestButtonActionPerformed
        try{
        if((!patientnameTextField.getText().isEmpty())&&(!ageTextField.getText().isEmpty())&&(!messageTextField.getText().isEmpty())){
        String name = patientnameTextField.getText();
        int age = Integer.parseInt(ageTextField.getText());
        String message = messageTextField.getText();
        String date = new java.text.SimpleDateFormat("MM/dd/yyyy").format(new Date());
        String time = new java.text.SimpleDateFormat("h:mm:ss a").format(new Date());
      
        DoctorTestWorkRequest request = new DoctorTestWorkRequest();
        request.setName(name);
        request.setAge(age);
        request.setSender(userAccount);
        request.setMessage(message);
        request.setDate(date);
        request.setTime(time);
        
        
        
        Organization org = null;
        for(Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof DoctorOrganization){
                org = organization;
                break;
            }
        }
        
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
            }
        JOptionPane.showMessageDialog(null, "Information Is Sent To Doctor","Success",JOptionPane.INFORMATION_MESSAGE);
        patientnameTextField.setText("");
        messageTextField.setText("");
        ageTextField.setText("");
            }
        else{
        JOptionPane.showMessageDialog(null, "Please Enter The Information To Send","Warning",JOptionPane.WARNING_MESSAGE);
        }
        
        }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(null, "Please Enter The Valid Information To Send","Warning",JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_requestTestButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ReceptionistWorkAreaJPanel rwjp = (ReceptionistWorkAreaJPanel) component;
        rwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backButtonActionPerformed

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed

    }//GEN-LAST:event_idTextFieldActionPerformed

    private void patientnameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_patientnameTextFieldKeyTyped

        char c = evt.getKeyChar();
        if(!(c=='a'||c=='b'||c=='c'||c=='d'||c=='e'||c=='f'||c=='g'||c=='h'||c=='i'||c=='j'||c=='k'||c=='l'||c=='m'||c=='n'||c=='o'||c=='p'||c=='q'||c=='r'||c=='s'||c=='t'||c=='u'||c=='v'||c=='w'||c=='x'||c=='y'||c=='z'||c=='A'||c=='B'||c=='C'||c=='D'||c=='E'||c=='F'||c=='G'||c=='H'||c=='I'||c=='J'||c=='K'||c=='L'||c=='M'||c=='N'||c=='O'||c=='P'||c=='Q'||c=='R'||c=='S'||c=='T'||c=='U'||c=='V'||c=='W'||c=='X'||c=='Y'||c=='Z'||c==KeyEvent.VK_BACKSPACE||c==KeyEvent.VK_DELETE||c==KeyEvent.VK_SPACE||c==KeyEvent.VK_SHIFT))
        {
        evt.consume();
        JOptionPane.showMessageDialog(null, "Please Enter Characters For Patient Name","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_patientnameTextFieldKeyTyped

    private void ageTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ageTextFieldKeyTyped

        int c = evt.getKeyChar();
        if(!(c=='0'||c=='1'||c=='2'||c=='3'||c=='4'||c=='5'||c=='6'||c=='7'||c=='8'||c=='9'||c==KeyEvent.VK_BACKSPACE||c==KeyEvent.VK_DELETE||c==KeyEvent.VK_SPACE||c==KeyEvent.VK_SHIFT))
        {
        evt.consume();
        JOptionPane.showMessageDialog(null, "Please Enter Integer For Age","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ageTextFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ageTextField;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField dateTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField messageTextField;
    private javax.swing.JTextField patientnameTextField;
    private javax.swing.JButton requestTestButton;
    private javax.swing.JTextField timeTextField;
    // End of variables declaration//GEN-END:variables
}
