/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ReceptionistRole;


import Business.Enterprise.Enterprise;
import Business.Organization.NurseOrganization;
import Business.WorkQueue.NurseTestWorkRequest;
import Business.Organization.Organization;
import Business.MainUserAccount.MainUserAccount;
import com.sun.glass.events.KeyEvent;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Achal Sancheti
 */
public class NurseTestWorkRequestJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private Enterprise enterprise;
    private MainUserAccount userAccount;

    /**
     * Creates new form NurseTestWorkRequestJPanel
     */
    public NurseTestWorkRequestJPanel(JPanel userProcessContainer, MainUserAccount account, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.userAccount = account;
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        donornameTextField = new javax.swing.JTextField();
        requestdateTextField = new javax.swing.JTextField();
        requestTestButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Donor Name");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Request Date");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        donornameTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                donornameTextFieldKeyTyped(evt);
            }
        });
        add(donornameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 94, -1));

        requestdateTextField.setEnabled(false);
        add(requestdateTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 94, -1));

        requestTestButton.setBackground(new java.awt.Color(0, 0, 0));
        requestTestButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        requestTestButton.setForeground(new java.awt.Color(255, 255, 255));
        requestTestButton.setText("Request Test");
        requestTestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestTestButtonActionPerformed(evt);
            }
        });
        add(requestTestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, 40));

        backButton.setBackground(new java.awt.Color(0, 0, 0));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("<<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 420, -1, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("ID");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, -1, -1));

        idTextField.setEnabled(false);
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });
        add(idTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 90, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/blood.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requestTestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestTestButtonActionPerformed

            if((!donornameTextField.getText().isEmpty())){
        
        
        String name = donornameTextField.getText();
        
        String date = new java.text.SimpleDateFormat("MM/dd/yyyy").format(new Date());
        String time = new java.text.SimpleDateFormat("h:mm:ss a").format(new Date());
        
        NurseTestWorkRequest request = new NurseTestWorkRequest();
        request.setName(name);
        request.setSender(userAccount);
        request.setStatus("Sent");
        request.setDate(date);
        request.setTime(time);
        
        Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof NurseOrganization){
                org = organization;
                break;
            }
                
        }
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(request);
            userAccount.getWorkQueue().getWorkRequestList().add(request);
        }
        
        JOptionPane.showMessageDialog(null, "Information Is Sent To Nurse","Success",JOptionPane.INFORMATION_MESSAGE);
        donornameTextField.setText("");
            }
        else{
        JOptionPane.showMessageDialog(null, "Please Enter The Information To Send","Warning",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_requestTestButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ReceptionistDonorJPanel rwjp = (ReceptionistDonorJPanel) component;
        rwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);

    }//GEN-LAST:event_backButtonActionPerformed

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        
    }//GEN-LAST:event_idTextFieldActionPerformed

    private void donornameTextFieldKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_donornameTextFieldKeyTyped
        
        char c = evt.getKeyChar();
        if(!(c=='a'||c=='b'||c=='c'||c=='d'||c=='e'||c=='f'||c=='g'||c=='h'||c=='i'||c=='j'||c=='k'||c=='l'||c=='m'||c=='n'||c=='o'||c=='p'||c=='q'||c=='r'||c=='s'||c=='t'||c=='u'||c=='v'||c=='w'||c=='x'||c=='y'||c=='z'||c=='A'||c=='B'||c=='C'||c=='D'||c=='E'||c=='F'||c=='G'||c=='H'||c=='I'||c=='J'||c=='K'||c=='L'||c=='M'||c=='N'||c=='O'||c=='P'||c=='Q'||c=='R'||c=='S'||c=='T'||c=='U'||c=='V'||c=='W'||c=='X'||c=='Y'||c=='Z'||c==KeyEvent.VK_BACKSPACE||c==KeyEvent.VK_DELETE||c==KeyEvent.VK_SPACE||c==KeyEvent.VK_SHIFT))
        {
        evt.consume();
        JOptionPane.showMessageDialog(null, "Please Enter Characters For Donor Name","Error",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_donornameTextFieldKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JTextField donornameTextField;
    private javax.swing.JTextField idTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton requestTestButton;
    private javax.swing.JTextField requestdateTextField;
    // End of variables declaration//GEN-END:variables
}
