/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.HospitalAdminRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Achal Sancheti
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    Enterprise enterprise;
    EcoSystem business;

    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public AdminWorkAreaJPanel(JPanel userProcessContainer, Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.enterprise = enterprise;
        this.business=business;
        valueLabel.setText(enterprise.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        manageuseraccountButton = new javax.swing.JButton();
        manageemployeeButton = new javax.swing.JButton();
        manageorganizationButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        manageuseraccountButton.setBackground(new java.awt.Color(0, 0, 0));
        manageuseraccountButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manageuseraccountButton.setForeground(new java.awt.Color(255, 255, 255));
        manageuseraccountButton.setText("Manage User Account");
        manageuseraccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageuseraccountButtonActionPerformed(evt);
            }
        });
        add(manageuseraccountButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, 180, 40));

        manageemployeeButton.setBackground(new java.awt.Color(0, 0, 0));
        manageemployeeButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manageemployeeButton.setForeground(new java.awt.Color(255, 255, 255));
        manageemployeeButton.setText("Manage Employee");
        manageemployeeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageemployeeButtonActionPerformed(evt);
            }
        });
        add(manageemployeeButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 350, 180, 40));

        manageorganizationButton.setBackground(new java.awt.Color(0, 0, 0));
        manageorganizationButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        manageorganizationButton.setForeground(new java.awt.Color(255, 255, 255));
        manageorganizationButton.setText("Manage Organization");
        manageorganizationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageorganizationButtonActionPerformed(evt);
            }
        });
        add(manageorganizationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 280, 180, 40));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(0, 0, 153));
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 120, 20));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(0, 0, 153));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 130, -1));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, -1, 460));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Admin Panel.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Admin.jpg"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void manageuseraccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageuseraccountButtonActionPerformed
        
        ManageUserAccountJPanel muajp = new ManageUserAccountJPanel(userProcessContainer, enterprise,business);
        userProcessContainer.add("ManageUserAccountJPanel", muajp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageuseraccountButtonActionPerformed

    private void manageemployeeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageemployeeButtonActionPerformed

        ManageEmployeeJPanel mejp = new ManageEmployeeJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("ManageEmployeeJPanel", mejp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageemployeeButtonActionPerformed

    private void manageorganizationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageorganizationButtonActionPerformed

        ManageOrganizationJPanel mojp = new ManageOrganizationJPanel(userProcessContainer, enterprise.getOrganizationDirectory());
        userProcessContainer.add("ManageOrganizationJPanel",mojp);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageorganizationButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton manageemployeeButton;
    private javax.swing.JButton manageorganizationButton;
    private javax.swing.JButton manageuseraccountButton;
    private javax.swing.JLabel valueLabel;
    // End of variables declaration//GEN-END:variables
}
