/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ReceptionistRole;

import Business.Enterprise.Enterprise;
import Business.Organization.ReceptionistOrganization;
import Business.MainUserAccount.MainUserAccount;
import Business.WorkQueue.NurseTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Achal Sancheti
 */
public class ReceptionistDonorJPanel extends javax.swing.JPanel {

    private JPanel userProcessContainer;
    private ReceptionistOrganization organization;
    private Enterprise enterprise;
    private MainUserAccount userAccount;
    /**
     * Creates new form ReceptionistDonorJPanel
     */
    public ReceptionistDonorJPanel(JPanel userProcessContainer, MainUserAccount account, ReceptionistOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        valueLabel.setText(enterprise.getName());
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            if(request instanceof NurseTestWorkRequest){
            
            Object[] row = new Object[8];
            
            row[0] = request;
            row[1] = request.getID();
            row[2] = request.getReceiver();
            row[3] = request.getStatus();
            String result = ((NurseTestWorkRequest) request).getBloodGroup();
            row[4] = result == null ? "Waiting" : result;
            int barcode = ((NurseTestWorkRequest) request).getBarCode();
            row[5] = result == null ? "Updating" : barcode;
            row[6] = request.getDate();
            row[7] = request.getTime();
            
            model.addRow(row);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestTable = new javax.swing.JTable();
        valueLabel = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        searchbyidButton = new javax.swing.JButton();
        searchbyTextField = new javax.swing.JTextField();
        requesttestButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Donor Name", "ID", "Receiver", "Status", "Blood Group", "Bar Code", "Request Date", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 930, 160));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(0, 0, 153));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 130, -1));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(0, 0, 153));
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 120, 20));

        searchbyidButton.setBackground(new java.awt.Color(0, 0, 0));
        searchbyidButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchbyidButton.setForeground(new java.awt.Color(255, 255, 255));
        searchbyidButton.setText("Search");
        searchbyidButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbyidButtonActionPerformed(evt);
            }
        });
        add(searchbyidButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 340, 140, 30));
        add(searchbyTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 340, 130, 30));

        requesttestButton.setBackground(new java.awt.Color(0, 0, 0));
        requesttestButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        requesttestButton.setForeground(new java.awt.Color(255, 255, 255));
        requesttestButton.setText("Request Test");
        requesttestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requesttestButtonActionPerformed(evt);
            }
        });
        add(requesttestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 340, -1, 32));

        backButton.setBackground(new java.awt.Color(0, 0, 0));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("<<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void searchbyidButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbyidButtonActionPerformed
        
        String key = searchbyTextField.getText();
        if(key.length()==0 || key==null){
                 JOptionPane.showMessageDialog(null, "Please Enter Your ID Number","Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
        WorkRequest info=userAccount.getWorkQueue().searchByName(key);
        if(info!=null){
         ViewDetailsJPanel view = new ViewDetailsJPanel(userProcessContainer, info);
         userProcessContainer.add("viewdetailsJPanel",view);
         CardLayout layout = (CardLayout)userProcessContainer.getLayout();
         layout.next(userProcessContainer);
         searchbyTextField.setText("");
        }
        else{
         JOptionPane.showMessageDialog(null, "This Profile Does Not Exist","Error", JOptionPane.ERROR_MESSAGE);
        searchbyTextField.setText("");
        }
        }
    }//GEN-LAST:event_searchbyidButtonActionPerformed

    private void requesttestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requesttestButtonActionPerformed
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestLabTestJPanel", new NurseTestWorkRequestJPanel(userProcessContainer, userAccount, enterprise));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requesttestButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton requesttestButton;
    private javax.swing.JTextField searchbyTextField;
    private javax.swing.JButton searchbyidButton;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestTable;
    // End of variables declaration//GEN-END:variables
}
