/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ReceptionistRole;


import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.ReceptionistOrganization;
import Business.MainUserAccount.MainUserAccount;
import Business.WorkQueue.DoctorTestWorkRequest;
import Business.WorkQueue.WorkRequest;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Achal Sancheti
 */
public class ReceptionistWorkAreaJPanel extends javax.swing.JPanel {
    
    private JPanel userProcessContainer;
    private ReceptionistOrganization organization;
    private Enterprise enterprise;
    private MainUserAccount userAccount;
    private EcoSystem business;

    /**
     * Creates new form ReceptionistWorkAreaJPanel
     */
    public ReceptionistWorkAreaJPanel(JPanel userProcessContainer, MainUserAccount account, ReceptionistOrganization organization, Enterprise enterprise) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organization = organization;
        this.enterprise = enterprise;
        this.userAccount = account;
        valueLabel.setText(enterprise.getName());
        populateTable();
    }
    
    public void populateTable(){
        DefaultTableModel model = (DefaultTableModel) workRequestTable.getModel();
        
        model.setRowCount(0);
        for (WorkRequest request : userAccount.getWorkQueue().getWorkRequestList()){
            if(request instanceof DoctorTestWorkRequest){
            Object[] row = new Object[6];
            
            row[0] = request;
            row[1] = request.getID();
            row[2] = request.getAge();
            row[3] = request.getReceiver();
            row[4] = request.getDate();
            row[5] = request.getTime();
            
            model.addRow(row);}
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        workRequestTable = new javax.swing.JTable();
        requesttestButton = new javax.swing.JButton();
        enterpriseLabel = new javax.swing.JLabel();
        valueLabel = new javax.swing.JLabel();
        searchTextField = new javax.swing.JTextField();
        searchbyidButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        workRequestTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient Name", "ID", "Age", "Receiver", "Date", "Time"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(workRequestTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 920, 160));

        requesttestButton.setBackground(new java.awt.Color(0, 0, 0));
        requesttestButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        requesttestButton.setForeground(new java.awt.Color(255, 255, 255));
        requesttestButton.setText("Request Test");
        requesttestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requesttestButtonActionPerformed(evt);
            }
        });
        add(requesttestButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 390, -1, 32));

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setForeground(new java.awt.Color(0, 0, 153));
        enterpriseLabel.setText("EnterPrise :");
        add(enterpriseLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 120, 20));

        valueLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        valueLabel.setForeground(new java.awt.Color(0, 0, 153));
        valueLabel.setText("<value>");
        add(valueLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 60, 130, -1));
        add(searchTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 400, 130, 30));

        searchbyidButton.setBackground(new java.awt.Color(0, 0, 0));
        searchbyidButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        searchbyidButton.setForeground(new java.awt.Color(255, 255, 255));
        searchbyidButton.setText("Search");
        searchbyidButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbyidButtonActionPerformed(evt);
            }
        });
        add(searchbyidButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 400, 140, 30));

        backButton.setBackground(new java.awt.Color(0, 0, 0));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("<<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 490, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/patient.jpg"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 110, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void requesttestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requesttestButtonActionPerformed
        
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        userProcessContainer.add("RequestLabTestJPanel", new DoctorTestWorkRequestJPanel(userProcessContainer, userAccount, enterprise));
        layout.next(userProcessContainer);
    }//GEN-LAST:event_requesttestButtonActionPerformed

    private void searchbyidButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchbyidButtonActionPerformed
        String key = searchTextField.getText();
        if(key.length()==0 || key==null){
                 JOptionPane.showMessageDialog(null, "Please Enter The Name","Error", JOptionPane.ERROR_MESSAGE);
        }
        else{
        WorkRequest info=userAccount.getWorkQueue().searchByName(key);
        if(info!=null){
         viewJPanel view = new viewJPanel(userProcessContainer, info);
         userProcessContainer.add("viewdetailsJPanel",view);
         CardLayout layout = (CardLayout)userProcessContainer.getLayout();
         layout.next(userProcessContainer);
         searchTextField.setText("");
        }
        else{
         JOptionPane.showMessageDialog(null, "This Profile Does Not Exist","Error", JOptionPane.ERROR_MESSAGE);
        searchTextField.setText("");
        }
        }
    }//GEN-LAST:event_searchbyidButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton requesttestButton;
    private javax.swing.JTextField searchTextField;
    private javax.swing.JButton searchbyidButton;
    private javax.swing.JLabel valueLabel;
    private javax.swing.JTable workRequestTable;
    // End of variables declaration//GEN-END:variables
}
