/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.FactoryAdminRole;

import Business.EcoSystem;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.Organization.OrganizationDirectory;
import Business.Role.ManagerRole;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Achal Sancheti
 */
public class ManageFactoryOrganizationJPanel extends javax.swing.JPanel {
    
    private OrganizationDirectory organizationDirectory;
    private JPanel userProcessContainer;
    private EcoSystem business;

    /**
     * Creates new form ManageOrganizationJPanel
     */
    public ManageFactoryOrganizationJPanel(JPanel userProcessContainer,OrganizationDirectory organizationDirectory) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDirectory = organizationDirectory;
        
        populateTable();
        populateCombo();
    }
    
    private void populateCombo(){
        organizationComboBox.removeAllItems();
        for (Organization.Type type : Organization.Type.values()){
            if (((!type.getValue().equals(Organization.Type.Admin.getValue()))&&
                    (!type.getValue().equals(Organization.Type.Patient.getValue()))&&
                    (!type.getValue().equals(Organization.Type.PatientRelative.getValue()))&&
                    (!type.getValue().equals(Organization.Type.Doctor.getValue()))&&
                    (!type.getValue().equals(Organization.Type.Donor.getValue()))&&
                    (!type.getValue().equals(Organization.Type.Nurse.getValue()))&&
                    (!type.getValue().equals(Organization.Type.Receptionist.getValue()))&&
                    (!type.getValue().equals(Organization.Type.VaccineManager.getValue()))))
                
                organizationComboBox.addItem(type);
        }
    }

    private void populateTable(){
        DefaultTableModel model = (DefaultTableModel) organizationTable.getModel();
        model.setRowCount(0);
        
        for (Organization organization : organizationDirectory.getOrganizationList()){
            Object[] row = new Object[2];
            row[0] = organization.getOrganizationID();
            row[1] = organization.getName();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        organizationTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        organizationComboBox = new javax.swing.JComboBox();
        addorganizationButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        organizationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Organization Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(organizationTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, 620, 130));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Organization Type");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, -1, -1));

        organizationComboBox.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        organizationComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(organizationComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 135, 35));

        addorganizationButton.setBackground(new java.awt.Color(0, 0, 0));
        addorganizationButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addorganizationButton.setForeground(new java.awt.Color(255, 255, 255));
        addorganizationButton.setText("Add Organization");
        addorganizationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addorganizationButtonActionPerformed(evt);
            }
        });
        add(addorganizationButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 420, -1, 35));

        backButton.setBackground(new java.awt.Color(0, 0, 0));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("<< Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, -1, 35));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 60, -1, 450));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/organizationn.jpg"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 30, 570, 450));
    }// </editor-fold>//GEN-END:initComponents

    private void addorganizationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addorganizationButtonActionPerformed
        Type type = (Type) organizationComboBox.getSelectedItem();

        if (!organizationDirectory.getOrganizationList().isEmpty()) {
            Boolean organizationFlag = false;
            for (Organization net : organizationDirectory.getOrganizationList()) {
                if (net.getName().equalsIgnoreCase(type.getValue())) {

                    JOptionPane.showMessageDialog(null, " The organization  "
                            + "already exists.", "Warning",
                            JOptionPane.WARNING_MESSAGE);
                    organizationFlag = true;
                    break;
                }

            }
            if (!organizationFlag) {
                Organization o = organizationDirectory.createOrganization(type);
                JOptionPane.showMessageDialog(null, "Organization Has Been Added Successfully","Success",JOptionPane.INFORMATION_MESSAGE);
        }
        } else {

            Organization o = organizationDirectory.createOrganization(type);
            JOptionPane.showMessageDialog(null, "Organization Has Been Added Successfully","Success",JOptionPane.INFORMATION_MESSAGE);
            populateTable();
        }
    }//GEN-LAST:event_addorganizationButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addorganizationButton;
    private javax.swing.JButton backButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox organizationComboBox;
    private javax.swing.JTable organizationTable;
    // End of variables declaration//GEN-END:variables
}
