/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import Business.Enterprise.Enterprise;
import Business.MainUserAccount.MainUserAccount;
import Business.Organization.Organization;
import Business.Organization.PatientRelativeOrganization;
import Business.WorkQueue.DoorWorkRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Achal Sancheti
 */
public class AddDoorJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    MainUserAccount account;
    Enterprise enterprise;

    /**
     * Creates new form AddDoorJPanel
     */
    public AddDoorJPanel(JPanel userProcessContainer,MainUserAccount account,Enterprise enterprise) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.enterprise=enterprise;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        doorTextField = new javax.swing.JTextField();
        adddoorButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Door");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, -1, -1));
        add(doorTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 170, -1));

        adddoorButton.setBackground(new java.awt.Color(0, 0, 0));
        adddoorButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        adddoorButton.setForeground(new java.awt.Color(255, 255, 255));
        adddoorButton.setText("Add Door");
        adddoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adddoorButtonActionPerformed(evt);
            }
        });
        add(adddoorButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 110, 30));

        backButton.setBackground(new java.awt.Color(0, 0, 0));
        backButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 255, 255));
        backButton.setText("<<Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        add(backButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 460, -1, 33));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 60, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/door.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(655, 70, 490, 470));
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed

        userProcessContainer.remove(this);
        Component[] componentArray = userProcessContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageDoorsJPanel rwjp = (ManageDoorsJPanel) component;
        rwjp.populateTable();
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_backButtonActionPerformed

    private void adddoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adddoorButtonActionPerformed
        
            if(!doorTextField.getText().isEmpty()){
            String door = doorTextField.getText();
            String date = new java.text.SimpleDateFormat("MM/dd/yyyy").format(new Date());
            String time = new java.text.SimpleDateFormat("h:mm:ss a").format(new Date());
            
            DoorWorkRequest doorWorkRequest = new DoorWorkRequest();
            doorWorkRequest.setDoor(door);
            doorWorkRequest.setDate(date);
            doorWorkRequest.setTime(time);
            doorWorkRequest.setStatus("Unlocked");
        
            Organization org = null;
        for (Organization organization : enterprise.getOrganizationDirectory().getOrganizationList()){
            if (organization instanceof PatientRelativeOrganization){
                org = organization;
                break;
            }
        }
        
        if (org!=null){
            org.getWorkQueue().getWorkRequestList().add(doorWorkRequest);
            account.getWorkQueue().getWorkRequestList().add(doorWorkRequest);
        }
        
        JOptionPane.showMessageDialog(null, "Door Has Been Added In The SmartWatch","Success",JOptionPane.INFORMATION_MESSAGE);
        doorTextField.setText("");
        }
            else{
            JOptionPane.showMessageDialog(null, "Please Enter The Door","Error",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_adddoorButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton adddoorButton;
    private javax.swing.JButton backButton;
    private javax.swing.JTextField doorTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
