/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.MainUserAccount.MainUserAccount;
import Business.Organization.Organization;
import Business.Organization.PatientOrganization;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Achal Sancheti
 */
public class PatientWorkAreaJPanel extends javax.swing.JPanel {
    
    JPanel userProcessContainer;
    MainUserAccount account;
    Organization organization;
    Enterprise enterprise;
    PatientOrganization patientOrganization;
    EcoSystem business;

    /**
     * Creates new form PatientWorkAreaJPanel
     */
    public PatientWorkAreaJPanel(JPanel userProcessContainer,MainUserAccount account,Organization organization,Enterprise enterprise,EcoSystem business) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.account=account;
        this.organization=organization;
        this.enterprise=enterprise;
        this.business=business;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vitalsignButton = new javax.swing.JButton();
        smartwatchButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        vitalsignButton.setBackground(new java.awt.Color(0, 0, 0));
        vitalsignButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        vitalsignButton.setForeground(new java.awt.Color(255, 255, 255));
        vitalsignButton.setText("See Vital Sign");
        vitalsignButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vitalsignButtonActionPerformed(evt);
            }
        });
        add(vitalsignButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 200, 160, 40));

        smartwatchButton.setBackground(new java.awt.Color(0, 0, 0));
        smartwatchButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        smartwatchButton.setForeground(new java.awt.Color(255, 255, 255));
        smartwatchButton.setText("Smart Watch");
        smartwatchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                smartwatchButtonActionPerformed(evt);
            }
        });
        add(smartwatchButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 160, 40));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("Welcome To The World Of Smart Watch");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, -1, -1));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 140, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/smartwatch.jpg"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 150, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void vitalsignButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vitalsignButtonActionPerformed
        
        ManagePatientJPanel managePatientJPanel = new ManagePatientJPanel(userProcessContainer, enterprise,account, (PatientOrganization) organization);
            userProcessContainer.add("ManagePatientJPanel", managePatientJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_vitalsignButtonActionPerformed

    private void smartwatchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_smartwatchButtonActionPerformed
      
            SmartWatchJPanel smartWatchJPanel = new SmartWatchJPanel(userProcessContainer, enterprise,account, (PatientOrganization) organization,business);
            userProcessContainer.add("SmartWatchJPanel", smartWatchJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
    }//GEN-LAST:event_smartwatchButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JButton smartwatchButton;
    private javax.swing.JButton vitalsignButton;
    // End of variables declaration//GEN-END:variables
}
