/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import java.io.File;
import java.util.Properties;
import javax.activation.DataHandler;
import javax.activation.FileDataSource;
import javax.mail.Message;
import javax.mail.PasswordAuthentication;
import javax.mail.*;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeBodyPart;
import javax.mail.internet.MimeMessage;
import javax.mail.internet.MimeMultipart;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Achal Sancheti
 */
public class SendEmailJFrame extends javax.swing.JFrame {

    /**
     * Creates new form SendEmailJFrame
     */
    public SendEmailJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        mailarea = new javax.swing.JTextArea();
        subjectTextField = new javax.swing.JTextField();
        toTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        mailButton = new javax.swing.JButton();
        fromTextField = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        attachButton = new javax.swing.JButton();
        path_attach = new javax.swing.JTextField();
        name_attach = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mailarea.setColumns(20);
        mailarea.setRows(5);
        jScrollPane1.setViewportView(mailarea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, 297, 236));
        getContentPane().add(subjectTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 300, -1));
        getContentPane().add(toTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 300, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("To:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Subject:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        mailButton.setBackground(new java.awt.Color(0, 0, 0));
        mailButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        mailButton.setForeground(new java.awt.Color(255, 255, 255));
        mailButton.setText("Mail");
        mailButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailButtonActionPerformed(evt);
            }
        });
        getContentPane().add(mailButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 200, 33));
        getContentPane().add(fromTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 30, 300, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("From:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        attachButton.setBackground(new java.awt.Color(0, 0, 0));
        attachButton.setForeground(new java.awt.Color(255, 255, 255));
        attachButton.setText("Attach");
        attachButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attachButtonActionPerformed(evt);
            }
        });
        getContentPane().add(attachButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 380, 120, 33));
        getContentPane().add(path_attach, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, 300, 30));
        getContentPane().add(name_attach, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 300, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Attachment Name:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mailButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailButtonActionPerformed

        String from = fromTextField.getText();
        String to = toTextField.getText();
        String subject = subjectTextField.getText();
        String body = mailarea.getText();
        
        
        Properties props = new Properties();
        props.put("mail.smtp.host","smtp.gmail.com");
        props.put("mail.smtp.socketFactory.port", "465");
        props.put("mail.smtp.socketFactory.class", "javax.net.ssl.SSLSocketFactory");
        props.put("mail.smtp.auth","true");
        props.put("mail.smtp.port","465");
        
        Session session = Session.getDefaultInstance(props,
                new javax.mail.Authenticator() {
                protected PasswordAuthentication getPasswordAuthentication(){
                return new PasswordAuthentication("achalsancheti@gmail.com", "ps991234");
                }
                }
                );
        
        try{
        
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress(from));
            message.setRecipients(Message.RecipientType.TO, InternetAddress.parse(to));
            message.setSubject(subject);
            
            MimeBodyPart messageBodyPart = new MimeBodyPart();
            messageBodyPart.setText(body);
            Multipart multipart = new MimeMultipart();
            multipart.addBodyPart(messageBodyPart);
            
            messageBodyPart = new MimeBodyPart();
            javax.activation.DataSource source = new FileDataSource(Attachment_path);
            messageBodyPart.setDataHandler(new DataHandler(source));
            messageBodyPart.setFileName(name_attach.getText());
            multipart.addBodyPart(messageBodyPart);
            message.setContent(multipart);
            
            Transport.send(message);
            JOptionPane.showMessageDialog(null, "Email Sent Successfully","Success",JOptionPane.INFORMATION_MESSAGE);
            fromTextField.setText("");
            toTextField.setText("");
            subjectTextField.setText("");
            mailarea.setText("");
            path_attach.setText("");
            name_attach.setText("");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please Fill All The Fields","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_mailButtonActionPerformed

    private void attachButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attachButtonActionPerformed
        
        try{
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        Attachment_path = f.getAbsolutePath();
        path_attach.setText(Attachment_path);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Please Fill All The Fields","Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_attachButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SendEmailJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SendEmailJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SendEmailJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SendEmailJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SendEmailJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton attachButton;
    private javax.swing.JTextField fromTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mailButton;
    private javax.swing.JTextArea mailarea;
    private javax.swing.JTextField name_attach;
    private javax.swing.JTextField path_attach;
    private javax.swing.JTextField subjectTextField;
    private javax.swing.JTextField toTextField;
    // End of variables declaration//GEN-END:variables

    String Attachment_path;

}
