/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.PatientRole;

import com.teknikindustries.yahooweather.WeatherDisplay;
import com.teknikindustries.yahooweather.WeatherDoc;

/**
 *
 * @author Achal Sancheti
 */
public class TemperatureJFrame extends javax.swing.JFrame {

    /**
     * Creates new form TemperatureJFrame
     */
    public TemperatureJFrame() {
        initComponents();
        temp();
    }
    
    private void temp(){
        WeatherDoc doc = new WeatherDoc("12758719", "c");
        WeatherDisplay disp = new WeatherDisplay();
        
        temp.setText(disp.getTemperature());
        city.setText(disp.getCity());
        humid.setText(disp.getHumidity());
        condition.setText(disp.getCondition());
        country.setText(disp.getCountry());
        windSpeed.setText(disp.getWindSpeed());
        windDirection.setText(disp.getWindDirection());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        country1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        temp = new javax.swing.JLabel();
        humid = new javax.swing.JLabel();
        condition = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        country = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        windSpeed = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        windDirection = new javax.swing.JLabel();
        degree = new javax.swing.JLabel();
        city = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        jLabel10.setText("jLabel10");

        jLabel12.setText("jLabel12");

        jLabel13.setText("jLabel13");

        country1.setBackground(new java.awt.Color(255, 255, 255));
        country1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        country1.setText("jLabel5");

        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(null);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Temperature(in C):");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 70, 190, 22);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Humidity:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 100, 88, 22);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Condition:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 130, 93, 22);

        temp.setBackground(new java.awt.Color(255, 255, 255));
        temp.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        temp.setText("jLabel4");
        getContentPane().add(temp);
        temp.setBounds(210, 70, 66, 22);

        humid.setBackground(new java.awt.Color(255, 255, 255));
        humid.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        humid.setText("jLabel4");
        getContentPane().add(humid);
        humid.setBounds(210, 100, 66, 22);

        condition.setBackground(new java.awt.Color(255, 255, 255));
        condition.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        condition.setText("jLabel4");
        getContentPane().add(condition);
        condition.setBounds(210, 130, 180, 22);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Country:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 10, 79, 22);

        country.setBackground(new java.awt.Color(255, 255, 255));
        country.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        country.setText("jLabel5");
        getContentPane().add(country);
        country.setBounds(210, 10, 170, 22);

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Wind Speed:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 160, 114, 22);

        windSpeed.setBackground(new java.awt.Color(255, 255, 255));
        windSpeed.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        windSpeed.setText("jLabel6");
        getContentPane().add(windSpeed);
        windSpeed.setBounds(210, 160, 66, 22);

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Wind Direction:");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 190, 142, 22);

        windDirection.setBackground(new java.awt.Color(255, 255, 255));
        windDirection.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        windDirection.setText("jLabel7");
        getContentPane().add(windDirection);
        windDirection.setBounds(210, 190, 66, 22);

        degree.setBackground(new java.awt.Color(255, 255, 255));
        degree.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        degree.setText("Degree");
        getContentPane().add(degree);
        degree.setBounds(230, 70, 66, 22);

        city.setBackground(new java.awt.Color(255, 255, 255));
        city.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        city.setText("jLabel7");
        getContentPane().add(city);
        city.setBounds(210, 40, 66, 22);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("City:");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(10, 40, 41, 22);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UserInterface/PatientRole/climate_change_tornado.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, -20, 600, 430);

        jLabel9.setText("jLabel9");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(260, 80, 34, 14);

        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(270, 70, 40, 14);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TemperatureJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TemperatureJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TemperatureJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TemperatureJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TemperatureJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel city;
    private javax.swing.JLabel condition;
    private javax.swing.JLabel country;
    private javax.swing.JLabel country1;
    private javax.swing.JLabel degree;
    private javax.swing.JLabel humid;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel temp;
    private javax.swing.JLabel windDirection;
    private javax.swing.JLabel windSpeed;
    // End of variables declaration//GEN-END:variables
}
